### ISSUE TITLE
foreach not working on blade template

### ISSUE THREAD

**Issue by fsuuaas** [harimayco/wmenu-builder#4]
"Trying to get property of non-object (View: F:\xampp\htdocs\wmenu-builder\resources\views\layouts\app.blade.php) (View: F:\xampp\htdocs\wmenu-builder\resources\views\layouts\app.blade.php)

```
@foreach($menuList as $main)
<li><a href="{{ $main->link }}">{{ $main->label }}</a></li>
@endforeach
```

**Comment by harimayco** [comment]
Have you tried debug or dump the $menuList?

On Sep 27, 2017 1:28 AM, "Sharif Uddin Ahamed" <notifications@github.com>
wrote:

"Trying to get property of non-object (View: F:\xampp\htdocs\wmenu-builder\
resources\views\layouts\app.blade.php) (View: F:\xampp\htdocs\wmenu-builder\
resources\views\layouts\app.blade.php)

@foreach <https://github.com/foreach>($menuList as $main)
- {{ $main->label }} @endforeach

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/harimayco/wmenu-builder/issues/4>, or mute the thread

**Comment by fsuuaas** [comment]
I tried. if I trying dd($main); it's ok, but if I try dd($main->link) it's  showing non object poperty

**Comment by harimayco** [comment]
I see. If youre using Menu::list it returns array not object.
You have to use $main['link'] instead of $main->link because it's an array not object.
